---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moviefun-pks
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: moviefun-pks
  targetCPUUtilizationPercentage: 80
